# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27c93e6c031cb77378d67e9f55215cd03dc6d809bd82dee180b1339ab8d81439a614b844355f2bf76bbe98e26a9bb79921a01a832fc5aeff095928efaa0728dc

test:
  secret_key_base: f2ea16a84d582e38e5b1b952c900483370a9bf5d7e71f9dd68922d32d8182cdddce64f7207134d7428a395c56703c21e7c9dd931863cc585efa91a8a438d70c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
